CREATE TABLE user_notifications (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    notification_type VARCHAR(50) NOT NULL,
    title VARCHAR(160) NOT NULL,
    message VARCHAR(500) NOT NULL,
    related_report_id BIGINT,
    related_generated_report_id BIGINT,
    created_at TIMESTAMPTZ NOT NULL,
    read_at TIMESTAMPTZ,
    CONSTRAINT fk_notification_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
    CONSTRAINT fk_notification_report FOREIGN KEY (related_report_id) REFERENCES maintenance_reports(id) ON DELETE SET NULL,
    CONSTRAINT fk_notification_generated FOREIGN KEY (related_generated_report_id) REFERENCES generated_reports(id) ON DELETE SET NULL,
    CONSTRAINT ck_notification_type CHECK (notification_type IN (
        'REPORT_CONFIRMED','SCHEDULED_DOCUMENT_READY','SCHEDULE_FAILED','EMAIL_FAILED','REVIEW_REQUIRED'
    ))
);

CREATE INDEX ix_user_notifications_user_created ON user_notifications(user_id, created_at DESC);
