CREATE TABLE kpi_intelligence_profiles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    kpi_definition_id BIGINT NOT NULL UNIQUE,
    enabled BOOLEAN NOT NULL DEFAULT TRUE,
    expected_cadence_days INTEGER,
    forecast_horizon INTEGER NOT NULL DEFAULT 7,
    seasonal_period INTEGER,
    history_window_days INTEGER NOT NULL DEFAULT 365,
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL,
    version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT fk_mi_profile_kpi FOREIGN KEY (kpi_definition_id) REFERENCES kpi_definitions(id),
    CONSTRAINT ck_mi_expected_cadence CHECK (expected_cadence_days IS NULL OR expected_cadence_days BETWEEN 1 AND 365),
    CONSTRAINT ck_mi_forecast_horizon CHECK (forecast_horizon BETWEEN 1 AND 30),
    CONSTRAINT ck_mi_seasonal_period CHECK (seasonal_period IS NULL OR seasonal_period BETWEEN 2 AND 365),
    CONSTRAINT ck_mi_history_window CHECK (history_window_days BETWEEN 30 AND 3650)
);

CREATE TABLE maintenance_intelligence_analyses (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    analysis_id VARCHAR(64) NOT NULL UNIQUE,
    kpi_definition_id BIGINT NOT NULL,
    profile_version BIGINT NOT NULL,
    profile_snapshot JSONB NOT NULL,
    snapshot_schema_version INTEGER NOT NULL,
    window_start DATE NOT NULL,
    window_end DATE NOT NULL,
    generated_at TIMESTAMPTZ NOT NULL,
    completed_at TIMESTAMPTZ NOT NULL,
    duration_millis BIGINT NOT NULL,
    status VARCHAR(30) NOT NULL,
    technical_failure_code VARCHAR(80),
    technical_failure_message VARCHAR(500),
    usable_observation_count INTEGER NOT NULL DEFAULT 0,
    missing_observation_count INTEGER NOT NULL DEFAULT 0,
    cadence_state VARCHAR(30),
    cadence_basis VARCHAR(40),
    cadence_ambiguity VARCHAR(60),
    trend_direction VARCHAR(30),
    anomaly_state VARCHAR(30),
    anomaly_reason VARCHAR(100),
    latest_anomalous BOOLEAN,
    latest_anomaly_score NUMERIC(20,10),
    forecast_state VARCHAR(30),
    forecast_reason VARCHAR(100),
    selected_model_family VARCHAR(40),
    forecast_direction VARCHAR(30),
    forecast_horizon INTEGER,
    forecast_mae NUMERIC(20,10),
    forecast_rmse NUMERIC(20,10),
    forecast_smape NUMERIC(20,10),
    latest_entry_id BIGINT,
    latest_report_id BIGINT,
    latest_effective_date DATE,
    latest_actual_value NUMERIC(20,6),
    expectation_state VARCHAR(30),
    expectation_reason VARCHAR(100),
    expected_value NUMERIC(20,6),
    expected_lower_bound NUMERIC(20,6),
    expected_upper_bound NUMERIC(20,6),
    outside_expected_interval BOOLEAN,
    result_snapshot JSONB,
    contextualization_status VARCHAR(30) NOT NULL DEFAULT 'PENDING',
    contextualization_failure VARCHAR(500),
    CONSTRAINT fk_mi_analysis_kpi FOREIGN KEY (kpi_definition_id) REFERENCES kpi_definitions(id),
    CONSTRAINT fk_mi_analysis_entry FOREIGN KEY (latest_entry_id) REFERENCES kpi_entries(id) ON DELETE SET NULL,
    CONSTRAINT fk_mi_analysis_report FOREIGN KEY (latest_report_id) REFERENCES maintenance_reports(id) ON DELETE SET NULL,
    CONSTRAINT ck_mi_analysis_status CHECK (status IN ('COMPLETED','INSUFFICIENT_DATA','TECHNICAL_FAILURE')),
    CONSTRAINT ck_mi_context_status CHECK (contextualization_status IN ('PENDING','COMPLETED','FAILED','NOT_APPLICABLE'))
);

CREATE INDEX ix_mi_analysis_kpi_generated ON maintenance_intelligence_analyses(kpi_definition_id, generated_at DESC);

CREATE TABLE maintenance_intelligence_alerts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    kpi_definition_id BIGINT NOT NULL,
    analysis_id BIGINT NOT NULL,
    source_entry_id BIGINT NOT NULL,
    source_report_id BIGINT NOT NULL,
    alert_type VARCHAR(50) NOT NULL,
    attention_level VARCHAR(20) NOT NULL,
    observation_date DATE NOT NULL,
    actual_value NUMERIC(20,6) NOT NULL,
    anomalous BOOLEAN NOT NULL,
    anomaly_score NUMERIC(20,10),
    expected_value NUMERIC(20,6),
    expected_lower_bound NUMERIC(20,6),
    expected_upper_bound NUMERIC(20,6),
    outside_expected_interval BOOLEAN,
    trend_context VARCHAR(30) NOT NULL,
    forecast_direction_context VARCHAR(30) NOT NULL,
    selected_model_family VARCHAR(40),
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL,
    notification_status VARCHAR(20) NOT NULL DEFAULT 'PENDING',
    notification_failure VARCHAR(500),
    CONSTRAINT fk_mi_alert_kpi FOREIGN KEY (kpi_definition_id) REFERENCES kpi_definitions(id),
    CONSTRAINT fk_mi_alert_analysis FOREIGN KEY (analysis_id) REFERENCES maintenance_intelligence_analyses(id),
    CONSTRAINT fk_mi_alert_entry FOREIGN KEY (source_entry_id) REFERENCES kpi_entries(id),
    CONSTRAINT fk_mi_alert_report FOREIGN KEY (source_report_id) REFERENCES maintenance_reports(id),
    CONSTRAINT uq_mi_alert_observation_type UNIQUE (source_entry_id, alert_type),
    CONSTRAINT ck_mi_alert_type CHECK (alert_type IN ('STRONG_CONTEXTUAL_DEVIATION','ANOMALOUS_OBSERVATION','FORECAST_DEVIATION')),
    CONSTRAINT ck_mi_attention CHECK (attention_level IN ('HIGH','MEDIUM')),
    CONSTRAINT ck_mi_notification_status CHECK (notification_status IN ('PENDING','SENT','FAILED'))
);

CREATE INDEX ix_mi_alert_kpi_created ON maintenance_intelligence_alerts(kpi_definition_id, created_at DESC);

ALTER TABLE user_notifications ADD COLUMN related_intelligence_alert_id BIGINT;
ALTER TABLE user_notifications ADD CONSTRAINT fk_notification_mi_alert
    FOREIGN KEY (related_intelligence_alert_id) REFERENCES maintenance_intelligence_alerts(id) ON DELETE SET NULL;
ALTER TABLE user_notifications DROP CONSTRAINT ck_notification_type;
ALTER TABLE user_notifications ADD CONSTRAINT ck_notification_type CHECK (notification_type IN (
    'REPORT_CONFIRMED','SCHEDULED_DOCUMENT_READY','SCHEDULE_FAILED','EMAIL_FAILED','REVIEW_REQUIRED',
    'MAINTENANCE_INTELLIGENCE_ATTENTION'
));
CREATE UNIQUE INDEX uq_notification_mi_alert ON user_notifications(related_intelligence_alert_id)
    WHERE related_intelligence_alert_id IS NOT NULL;
