CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(150) NOT NULL,
    email VARCHAR(254) NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT ck_users_name_not_blank CHECK (LENGTH(BTRIM(name)) > 0),
    CONSTRAINT ck_users_email_not_blank CHECK (LENGTH(BTRIM(email)) > 0),
    CONSTRAINT ck_users_password_hash_not_blank CHECK (LENGTH(BTRIM(password_hash)) > 0)
);

CREATE UNIQUE INDEX uq_users_email_normalized ON users (LOWER(email));
