CREATE TABLE kpi_definitions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(100) NOT NULL,
    display_name VARCHAR(200) NOT NULL,
    category VARCHAR(150),
    unit VARCHAR(50),
    plausible_min NUMERIC(20,6),
    plausible_max NUMERIC(20,6),
    active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT uq_kpi_definitions_code UNIQUE (code),
    CONSTRAINT ck_kpi_definitions_code_not_blank CHECK (LENGTH(BTRIM(code)) > 0),
    CONSTRAINT ck_kpi_definitions_name_not_blank CHECK (LENGTH(BTRIM(display_name)) > 0),
    CONSTRAINT ck_kpi_plausible_range CHECK (
        plausible_min IS NULL OR plausible_max IS NULL OR plausible_min <= plausible_max
    )
);

CREATE TABLE kpi_aliases (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    kpi_definition_id BIGINT NOT NULL,
    alias VARCHAR(200) NOT NULL,
    normalized_alias VARCHAR(200) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT fk_kpi_alias_definition FOREIGN KEY (kpi_definition_id)
        REFERENCES kpi_definitions(id) ON DELETE CASCADE,
    CONSTRAINT uq_kpi_alias_normalized UNIQUE (normalized_alias),
    CONSTRAINT ck_kpi_alias_not_blank CHECK (LENGTH(BTRIM(alias)) > 0),
    CONSTRAINT ck_kpi_alias_normalized_not_blank CHECK (LENGTH(BTRIM(normalized_alias)) > 0)
);

CREATE INDEX ix_kpi_definitions_active ON kpi_definitions(active);

INSERT INTO kpi_definitions (code, display_name, category, unit, plausible_min, active) VALUES
    ('CHOLINE', 'Choline', 'Production', NULL, 0, TRUE),
    ('VRAC', 'Vrac', 'Production', 't', 0, TRUE),
    ('SAC', 'Sac', 'Production', 't', 0, TRUE),
    ('TOTAL', 'Total', 'Production', 't', 0, TRUE),
    ('FUEL', 'Fuel', 'Utilities', NULL, 0, TRUE),
    ('COMPRESSEUR_1', 'Compresseur 1', 'Utilities', NULL, 0, TRUE);

INSERT INTO kpi_aliases (kpi_definition_id, alias, normalized_alias)
SELECT id, 'Varc', 'varc' FROM kpi_definitions WHERE code = 'VRAC';

INSERT INTO kpi_aliases (kpi_definition_id, alias, normalized_alias)
SELECT id, 'Compresseur1', 'compresseur1' FROM kpi_definitions WHERE code = 'COMPRESSEUR_1';
