CREATE TABLE maintenance_reports (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    submitted_by BIGINT NOT NULL,
    effective_date DATE NOT NULL,
    submitted_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    raw_text TEXT,
    source VARCHAR(40) NOT NULL,
    status VARCHAR(40) NOT NULL,
    confirmed_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT fk_maintenance_report_user FOREIGN KEY (submitted_by) REFERENCES users(id),
    CONSTRAINT ck_maintenance_report_source CHECK (source IN ('MANUAL','PASTE','GALLERY_OCR','SHARE_OCR','CAMERA_OCR')),
    CONSTRAINT ck_maintenance_report_status CHECK (status IN ('DRAFT','PENDING_REVIEW','CONFIRMED')),
    CONSTRAINT ck_maintenance_report_confirmation CHECK (
        (status = 'CONFIRMED' AND confirmed_at IS NOT NULL) OR
        (status <> 'CONFIRMED' AND confirmed_at IS NULL)
    )
);

CREATE TABLE kpi_entries (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    report_id BIGINT NOT NULL,
    kpi_definition_id BIGINT,
    source_label VARCHAR(255),
    source_line TEXT,
    extracted_value NUMERIC(20,6),
    current_value NUMERIC(20,6),
    final_value NUMERIC(20,6),
    confidence_score NUMERIC(5,4),
    edited_by_user BOOLEAN NOT NULL DEFAULT FALSE,
    captured_unit VARCHAR(50),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT fk_kpi_entry_report FOREIGN KEY (report_id) REFERENCES maintenance_reports(id) ON DELETE CASCADE,
    CONSTRAINT fk_kpi_entry_definition FOREIGN KEY (kpi_definition_id) REFERENCES kpi_definitions(id),
    CONSTRAINT ck_kpi_entry_confidence CHECK (confidence_score IS NULL OR (confidence_score >= 0 AND confidence_score <= 1))
);

CREATE TABLE kpi_entry_warnings (
    kpi_entry_id BIGINT NOT NULL,
    warning_code VARCHAR(80) NOT NULL,
    CONSTRAINT fk_kpi_entry_warning FOREIGN KEY (kpi_entry_id) REFERENCES kpi_entries(id) ON DELETE CASCADE,
    CONSTRAINT uq_kpi_entry_warning UNIQUE (kpi_entry_id, warning_code)
);

CREATE TABLE report_unrecognized_lines (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    report_id BIGINT NOT NULL,
    source_line TEXT NOT NULL,
    resolution_status VARCHAR(40) NOT NULL,
    resolved_kpi_definition_id BIGINT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT fk_unrecognized_report FOREIGN KEY (report_id) REFERENCES maintenance_reports(id) ON DELETE CASCADE,
    CONSTRAINT fk_unrecognized_kpi FOREIGN KEY (resolved_kpi_definition_id) REFERENCES kpi_definitions(id),
    CONSTRAINT ck_unrecognized_resolution CHECK (resolution_status IN ('UNRESOLVED','ASSIGNED','IGNORED')),
    CONSTRAINT ck_unrecognized_assignment CHECK (
        (resolution_status = 'ASSIGNED' AND resolved_kpi_definition_id IS NOT NULL) OR
        (resolution_status <> 'ASSIGNED' AND resolved_kpi_definition_id IS NULL)
    )
);

CREATE INDEX ix_maintenance_reports_user_status ON maintenance_reports(submitted_by, status);
CREATE INDEX ix_maintenance_reports_effective_date ON maintenance_reports(effective_date);
CREATE INDEX ix_kpi_entries_report ON kpi_entries(report_id);
CREATE INDEX ix_unrecognized_lines_report ON report_unrecognized_lines(report_id);
