CREATE TABLE generated_reports (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    type VARCHAR(40) NOT NULL,
    format VARCHAR(20) NOT NULL,
    period_start DATE NOT NULL,
    period_end DATE NOT NULL,
    generated_at TIMESTAMPTZ NOT NULL,
    file_path TEXT NOT NULL,
    file_name VARCHAR(255) NOT NULL,
    generated_by BIGINT,
    origin VARCHAR(30) NOT NULL,
    generation_status VARCHAR(40) NOT NULL,
    email_delivery_status VARCHAR(40) NOT NULL,
    version INTEGER NOT NULL DEFAULT 1,
    regenerated_from_id BIGINT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT fk_generated_report_user FOREIGN KEY (generated_by) REFERENCES users(id),
    CONSTRAINT fk_generated_report_regeneration FOREIGN KEY (regenerated_from_id) REFERENCES generated_reports(id),
    CONSTRAINT ck_generated_report_period CHECK (period_start <= period_end),
    CONSTRAINT ck_generated_report_type CHECK (type IN ('DAILY','WEEKLY','MONTHLY','MANUAL')),
    CONSTRAINT ck_generated_report_format CHECK (format IN ('EXCEL')),
    CONSTRAINT ck_generated_report_origin CHECK (origin IN ('MANUAL')),
    CONSTRAINT ck_generated_report_status CHECK (generation_status IN ('READY','FAILED')),
    CONSTRAINT ck_generated_report_email_status CHECK (email_delivery_status IN ('NOT_REQUESTED')),
    CONSTRAINT ck_generated_report_version CHECK (version >= 1)
);

CREATE TABLE generated_report_sources (
    generated_report_id BIGINT NOT NULL,
    maintenance_report_id BIGINT NOT NULL,
    PRIMARY KEY (generated_report_id, maintenance_report_id),
    CONSTRAINT fk_generated_source_document FOREIGN KEY (generated_report_id)
        REFERENCES generated_reports(id) ON DELETE CASCADE,
    CONSTRAINT fk_generated_source_maintenance FOREIGN KEY (maintenance_report_id)
        REFERENCES maintenance_reports(id)
);

CREATE INDEX ix_generated_reports_generated_at ON generated_reports(generated_at DESC);
CREATE INDEX ix_generated_reports_type_period ON generated_reports(type, period_start, period_end);
