ALTER TABLE generated_reports DROP CONSTRAINT ck_generated_report_format;
ALTER TABLE generated_reports ADD CONSTRAINT ck_generated_report_format CHECK (format IN ('EXCEL','PDF'));
ALTER TABLE generated_reports DROP CONSTRAINT ck_generated_report_origin;
ALTER TABLE generated_reports ADD CONSTRAINT ck_generated_report_origin CHECK (origin IN ('MANUAL','SCHEDULED'));
ALTER TABLE generated_reports DROP CONSTRAINT ck_generated_report_email_status;
ALTER TABLE generated_reports ADD CONSTRAINT ck_generated_report_email_status
    CHECK (email_delivery_status IN ('NOT_REQUESTED','PENDING','DELIVERED','FAILED'));

CREATE TABLE report_schedules (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    schedule_type VARCHAR(30) NOT NULL,
    time_of_day TIME NOT NULL,
    day_of_week VARCHAR(20),
    enabled BOOLEAN NOT NULL DEFAULT TRUE,
    generate_excel BOOLEAN NOT NULL DEFAULT TRUE,
    generate_pdf BOOLEAN NOT NULL DEFAULT TRUE,
    email_enabled BOOLEAN NOT NULL DEFAULT FALSE,
    timezone VARCHAR(100) NOT NULL,
    created_by BIGINT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT fk_report_schedule_user FOREIGN KEY (created_by) REFERENCES users(id),
    CONSTRAINT ck_report_schedule_type CHECK (schedule_type IN ('DAILY','WEEKLY','MONTHLY')),
    CONSTRAINT ck_report_schedule_weekday CHECK (
        (schedule_type = 'WEEKLY' AND day_of_week IS NOT NULL) OR
        (schedule_type <> 'WEEKLY' AND day_of_week IS NULL)
    ),
    CONSTRAINT ck_report_schedule_format CHECK (generate_excel OR generate_pdf),
    CONSTRAINT ck_report_schedule_timezone CHECK (timezone = 'Africa/Casablanca')
);

CREATE TABLE report_schedule_recipients (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    schedule_id BIGINT NOT NULL,
    email VARCHAR(320) NOT NULL,
    CONSTRAINT fk_schedule_recipient FOREIGN KEY (schedule_id) REFERENCES report_schedules(id) ON DELETE CASCADE,
    CONSTRAINT uq_schedule_recipient UNIQUE (schedule_id, email)
);

CREATE TABLE schedule_runs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    schedule_id BIGINT NOT NULL,
    format VARCHAR(20) NOT NULL,
    period_start DATE NOT NULL,
    period_end DATE NOT NULL,
    scheduled_for TIMESTAMPTZ NOT NULL,
    started_at TIMESTAMPTZ NOT NULL,
    finished_at TIMESTAMPTZ,
    status VARCHAR(30) NOT NULL,
    generated_report_id BIGINT,
    email_delivery_status VARCHAR(40) NOT NULL DEFAULT 'NOT_REQUESTED',
    error_code VARCHAR(80),
    error_message VARCHAR(500),
    CONSTRAINT fk_schedule_run_schedule FOREIGN KEY (schedule_id) REFERENCES report_schedules(id),
    CONSTRAINT fk_schedule_run_generated FOREIGN KEY (generated_report_id) REFERENCES generated_reports(id),
    CONSTRAINT uq_schedule_run_period_format UNIQUE (schedule_id, period_start, period_end, format),
    CONSTRAINT ck_schedule_run_period CHECK (period_start <= period_end),
    CONSTRAINT ck_schedule_run_format CHECK (format IN ('EXCEL','PDF')),
    CONSTRAINT ck_schedule_run_status CHECK (status IN ('STARTED','SUCCEEDED','PARTIAL_SUCCESS','FAILED','SKIPPED')),
    CONSTRAINT ck_schedule_run_email_status CHECK (email_delivery_status IN ('NOT_REQUESTED','PENDING','DELIVERED','FAILED'))
);

ALTER TABLE generated_reports ADD COLUMN schedule_id BIGINT;
ALTER TABLE generated_reports ADD CONSTRAINT fk_generated_report_schedule
    FOREIGN KEY (schedule_id) REFERENCES report_schedules(id);

CREATE UNIQUE INDEX uq_generated_schedule_period_format
    ON generated_reports(schedule_id, period_start, period_end, format)
    WHERE schedule_id IS NOT NULL;
CREATE INDEX ix_report_schedules_enabled ON report_schedules(enabled);
CREATE INDEX ix_schedule_runs_schedule_started ON schedule_runs(schedule_id, started_at DESC);
CREATE INDEX ix_confirmed_entries_statistics
    ON maintenance_reports(status, effective_date, id);
CREATE INDEX ix_kpi_entries_definition_report
    ON kpi_entries(kpi_definition_id, report_id);
