package com.factoryflow.shared.error;

public enum ApiErrorCode {
    VALIDATION_ERROR,
    MALFORMED_REQUEST,
    AUTH_INVALID_CREDENTIALS,
    AUTH_UNAUTHORIZED,
    KPI_CODE_ALREADY_EXISTS,
    KPI_DEFINITION_NOT_FOUND,
    REPORT_NOT_FOUND,
    REPORT_ALREADY_CONFIRMED,
    REPORT_INVALID_STATE,
    REPORT_VALIDATION_FAILED,
    REPORT_GENERATION_FAILED,
    GENERATED_REPORT_NOT_FOUND,
    REPORT_FILE_NOT_FOUND,
    SCHEDULE_NOT_FOUND,
    SCHEDULE_VALIDATION_FAILED,
    CONFLICT,
    INTERNAL_ERROR
}
